name: TrinketsX
description: Este plugin es creado para el servidor Insomnia por GoldenShulkerStudios
author: ewahv1
main: me.ewahv1.plugin.Main
version: 1.0.0
api-version: 1.21
commands:
  bolsa:
    description: Abre la Bolsa de Trinkets
    usage: /bolsa