name: TrinketPlugin
description: This plugin is created for the Insomnia
author: ewahv1
main: me.ewahv1.plugin.Main
version: 0.0.1
api-version: 1.20
commands:
  bolsa:
    description: "Abre tu Bolsa de Trinkets."
    usage: "/bolsa"